const BookActionTypes = {
  LOCATIONS_FOUND: 'LOCATIONS_FOUND',
  LOCATIONS_CLEARED: 'LOCATIONS_CLEARED',
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  INPUT: 'BOOK_INPUT',
  SUCCESS: 'BOOK_SUCCESS',
  ERROR: 'BOOk_ERROR',
  SUBMIT: 'BOOK_SUBMIT',
}

export default BookActionTypes;