const BookActionTypes = {
  LOCATIONS_FOUND: 'LOCATIONS_FOUND',
  LOCATIONS_CLEARED: 'LOCATIONS_CLEARED',
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  INPUT: 'INPUT',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  SUBMIT: 'SUBMIT',
}

export default BookActionTypes;