import type { NextPage } from 'next';
import Head from 'next/head';
import LandingContainer from '../features/landing/components/landing.container';
import NavbarContainer from '../features/navbar';

const HomePage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<NavbarContainer />
			<LandingContainer />
		</div>
	);
};

export default HomePage;
